### ISSUE TITLE
to support docker run for luneos

### ISSUE THREAD

**Issue by gmicroul** [Moe-hacker/rurima#1]
<img width="511" alt="image" src="https://github.com/user-attachments/assets/057d8b05-49f5-4317-a91b-6bb9dd7ca4a6">

**Comment by Moe-hacker** [comment]
rurima has no relationship with docker, for now, it just provides a way to pull the image and parse the config from dockerhub. 
In the future, it might add more functions, to make it a partial replacement of docker, but as it will not support OCI or docker command-line arguments, it will not be a full replacement of docker and might need the user to solve problems in the container by themselves.
